@startuml
start
:Get release date from EMA PP Planning meeting;
if (TC impacted by release? Such as new price object added?) then(yes)
	:Collect input: Product Packaging Configuration Rule(Cecilia Nordquist);
	:Update "EMA Ericsson Development SW.xlsx";
else(yes)
	:Collect input: SVL(Yinghai & Toiwo);
	:Update "EMA15_3PPs_Commercial.xlsx";
	:Update "EMA15_3PPs_FOSS.xlsx";
endif
:Update 2400-FGC1012540.doc";
stop
@enduml