@startuml
start
if (Site TCA decide 2401 is required) then(yes)
	:Update 2401 based on 2400;
	:Send to site TCA for review;
	:Send to TC office for approval(External process);
	:Update Product Category with new Export Conditions;
else(no)
endif
stop
@enduml