@startuml

package "Some Group" {
  [mpe-services-nbia]
  [mpe-services-common]
  [mpe-services-req-controller]
  [mpe-platform-common]
  [mpe-platform-authentication]
  [mpe-business-nbi-cai3g1.2]
}
 

@enduml
		