@startuml

box "mpe-services-req-controller" #LightGreen
	participant ComponentBase
end box
box "Distribute MBean Configuration(eforge)" #Wheat
	participant ConfigurationManagerImpl
	participant ConfigurationDistributionManager
end box
box "JDK" #LightBlue
	participant JMX
end box

[-> ComponentBase: activate()
activate ComponentBase
ComponentBase -> ConfigurationManagerImpl: getConfig(RequestChain.class)
activate ConfigurationManagerImpl
note right
If it is the first time load component configuration, call createMBean
end note
ConfigurationManagerImpl -> ConfigurationManagerImpl: createMBean()
activate ConfigurationManagerImpl
ConfigurationManagerImpl -> ConfigurationManagerImpl: getAttributes(RequestChain.class)
activate ConfigurationManagerImpl
note left
Get attributes of the interface by reflection
end note
deactivate ConfigurationManagerImpl
ConfigurationManagerImpl -> ConfigurationDistributionManager: create()
activate ConfigurationDistributionManager
note left
Distribute component attribute by Zookeeper
end note
ConfigurationDistributionManager -> ConfigurationManagerImpl
deactivate ConfigurationDistributionManager
ConfigurationManagerImpl -> JMX: newMBeanProxy()
activate JMX
note left
Create a MBean proxy instance of interface
end note
JMX -> ConfigurationManagerImpl
deactivate JMX
deactivate ConfigurationManagerImpl
ConfigurationManagerImpl -> ComponentBase
deactivate ConfigurationManagerImpl

ComponentBase -> ComponentBase: initChain()
activate ComponentBase
note right
Initialize ComponentBase with the configuration data in MBean
end note
deactivate ComponentBase

deactivate ComponentBase

@enduml