@startuml
start

:Cutover primary & secondary PG;
note right
Primary PG is <b>NOT</b> isolated.
BOSS provision via secondary PG.
30 min
end note
:Data backup of primary PG;
note right
60 min
end note
while (start rolling upgrade each PL blade)
:Uninstall MCA21 CA;
note right
60 min
end note
:Uninstall MDE CA;
note right
60 min
end note
:Upgrade to PG 7.1 CP5;
note right
120 min
end note
:Upgrade to PG 7.1 CP5 ICP1;
note right
120 min
end note
:Install MDE CA;
note right
60 min
end note
:Install MCA21 CA;
note right
60 min
end note
:Install 4G MML CA;
note right
60 min
end note
:Provision testing on primary PG;
note right
120 min
end note
endwhile
:Cutover primary & secondary PG;
note right
Primary PG is back to function.
BOSS provision via primary PG.
60 min
end note
stop
@enduml