package org.apache.hello_world_async_soap_http;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.10
 * 2014-03-30T10:26:18.505+08:00
 * Generated source version: 2.7.10
 * 
 */
@WebServiceClient(name = "SOAPService", 
                  wsdlLocation = "hello_world_async.wsdl",
                  targetNamespace = "http://apache.org/hello_world_async_soap_http") 
public class SOAPService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://apache.org/hello_world_async_soap_http", "SOAPService");
    public final static QName SoapPort = new QName("http://apache.org/hello_world_async_soap_http", "SoapPort");
    static {
        URL url = SOAPService.class.getResource("hello_world_async.wsdl");
        if (url == null) {
            url = SOAPService.class.getClassLoader().getResource("hello_world_async.wsdl");
        } 
        if (url == null) {
            java.util.logging.Logger.getLogger(SOAPService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "hello_world_async.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public SOAPService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SOAPService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SOAPService() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns GreeterAsync
     */
    @WebEndpoint(name = "SoapPort")
    public GreeterAsync getSoapPort() {
        return super.getPort(SoapPort, GreeterAsync.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns GreeterAsync
     */
    @WebEndpoint(name = "SoapPort")
    public GreeterAsync getSoapPort(WebServiceFeature... features) {
        return super.getPort(SoapPort, GreeterAsync.class, features);
    }

}
