@startuml

[-> TargetCallable: handleResponse()
activate TargetCallable
note right
Refer to DVE core to JDV
Only when success response is returned, PG will update license counter 
end note
TargetCallable -> TargetCallable: modifyCapacityCounters()
activate TargetCallable
TargetCallable -> LicenseServiceImpl: increaseCapacityCounter()
activate LicenseServiceImpl
LicenseServiceImpl -> LicenseServiceImpl: modifyCounterValue()
activate LicenseServiceImpl
LicenseServiceImpl -> CapacityLicenseImpl: increaseCounter()
activate CapacityLicenseImpl
note left
Update delta usage(capacityCounter) in this PL node
end note
CapacityLicenseImpl -> LicenseServiceImpl
deactivate CapacityLicenseImpl
deactivate LicenseServiceImpl
LicenseServiceImpl -> TargetCallable
deactivate LicenseServiceImpl
deactivate TargetCallable
deactivate TargetCallable
@enduml