@startuml

box "DVE-OM-GUI-LIB" #LightGreen
	participant DataRepositoryDispatchAction
end box
box "LIB-PAS" #LightBlue
	participant JmxBackendImpl
	participant ConnectionPoolGuiVo
	participant DVEJmx
	participant JmxConnectionImpl
end box
box "DVE-Resource-Deployer" #LightYellow
	participant ConnectionPoolFactory
end box

[-> DataRepositoryDispatchAction: addTaskData()
activate DataRepositoryDispatchAction
DataRepositoryDispatchAction -> DataRepositoryDispatchAction: prepareNewDataRepository()
activate DataRepositoryDispatchAction
DataRepositoryDispatchAction -> JmxBackendImpl: add(ConnectionPoolGuiVo)
activate JmxBackendImpl
note right
DataRepositoryDispatchAction encapsulate a ConnectionPoolGuiVo
ConnectionPoolGuiVo is an instance of MBeanValueObject
DataRepositoryDispatchAction transfer ConnectionPoolGuiVo to JmxBackendImpl
end note
JmxBackendImpl -> ConnectionPoolGuiVo: add(ConnectionPoolFactoryMBean)
note right
JmxBackendImpl find a factory class for ConnectionPoolGuiVo in its mapping
ConnectionPoolFactoryMBean is factory of ConnectionPool
JmxBackendImpl lookup ConnectionPoolFactoryMBean instance in MBeanServer
The result is a ConnectionPoolFactory instance
end note
activate ConnectionPoolGuiVo
ConnectionPoolGuiVo -> ConnectionPoolGuiVo: addAsMBean(ConnectionPoolFactoryMBean)
activate ConnectionPoolGuiVo
ConnectionPoolGuiVo -> ConnectionPoolFactory: createConnectionPool()
activate ConnectionPoolFactory
note left
The connection pool is registered in MBeanServer
Its object name is stored in ConnectionPoolGuiVo
end note
ConnectionPoolFactory -> DVEJmx: createAndRegisterMBean()
activate DVEJmx
DVEJmx -> ConnectionPoolFactory
deactivate DVEJmx
ConnectionPoolFactory -> ConnectionPoolGuiVo
deactivate ConnectionPoolFactory
deactivate ConnectionPoolGuiVo
ConnectionPoolGuiVo -> JmxBackendImpl
deactivate ConnectionPoolGuiVo
JmxBackendImpl -> JmxBackendImpl: updateAfterAdd()
activate JmxBackendImpl
JmxBackendImpl -> JmxConnectionImpl: updateMBean()
activate JmxConnectionImpl
JmxConnectionImpl -> JmxBackendImpl
deactivate JmxConnectionImpl
deactivate JmxBackendImpl
JmxBackendImpl -> DataRepositoryDispatchAction
deactivate JmxBackendImpl
deactivate DataRepositoryDispatchAction
DataRepositoryDispatchAction -> DataRepositoryDispatchAction: processChangedConnectionPool()
note right
Store attributes of connection pool in its MBean
end note
activate DataRepositoryDispatchAction
deactivate DataRepositoryDispatchAction
deactivate DataRepositoryDispatchAction

@enduml