@startuml

box "DVE-Interface-MML" #LightGreen
	participant CliServer
	participant CliSocketSessionFactoryImpl
	participant CliSocketSessionImpl
	participant CliProtocolParserImpl
	participant RequestManagerImpl
	participant AsynchroneMmlRequest
end box

box "DVE core" #LightBlue
	participant DataViewEngine
end box

[-> CliServer: run()
activate CliServer
CliServer -> CliServer: serverRun()
CliServer -> CliSocketSessionFactoryImpl: startSocketSession()
note left
receive an incoming CLI request
end note
activate CliSocketSessionFactoryImpl
CliSocketSessionFactoryImpl -> CliSocketSessionImpl: start()
activate CliSocketSessionImpl
CliSocketSessionImpl -> CliSocketSessionImpl: run()
activate CliSocketSessionImpl
CliSocketSessionImpl -> CliSocketSessionImpl: processInput()
note left
if HECDAPI request comes in, get AsynchroneMmlRequest instance
end note
activate CliSocketSessionImpl
CliSocketSessionImpl -> CliProtocolParserImpl: getJobRequest()
activate CliProtocolParserImpl
CliProtocolParserImpl -> CliSocketSessionImpl
deactivate CliProtocolParserImpl
CliSocketSessionImpl -> RequestManagerImpl: processRequest()
activate RequestManagerImpl
RequestManagerImpl -> AsynchroneMmlRequest: execute()
activate AsynchroneMmlRequest
AsynchroneMmlRequest -> DataViewEngine: execute()
activate DataViewEngine
DataViewEngine -> AsynchroneMmlRequest
deactivate DataViewEngine
AsynchroneMmlRequest -> RequestManagerImpl
deactivate AsynchroneMmlRequest
RequestManagerImpl -> CliSocketSessionImpl
deactivate RequestManagerImpl
deactivate CliSocketSessionImpl
deactivate CliSocketSessionImpl
CliSocketSessionImpl -> CliSocketSessionFactoryImpl
deactivate CliSocketSessionImpl
CliSocketSessionFactoryImpl -> CliServer
deactivate CliSocketSessionFactoryImpl
deactivate CliServer

@enduml