@startuml
box "LIB-PAS" #LightBlue
	participant AnnotatedDynamicMBean
	participant GenericConnectionPool
end box
box "DVE-Resource-Deployer" #LightYellow
	participant ConnectorDeployerImpl
	participant ConnectionPoolRegistry
	participant ConnectionPool
end box
box "JDK" #LightGrey
	participant MBeanServer
end box

[-> AnnotatedDynamicMBean: preRegister()
activate AnnotatedDynamicMBean
AnnotatedDynamicMBean -> GenericConnectionPool: startup()
activate GenericConnectionPool
GenericConnectionPool -> GenericConnectionPool: createResourceBean()
activate GenericConnectionPool
note right
ResourceBean contains the attributes of connection pool
end note
deactivate GenericConnectionPool
GenericConnectionPool -> ConnectorDeployerImpl: deploy(ResourceBean)
activate ConnectorDeployerImpl
ConnectorDeployerImpl -> ConnectorDeployerImpl: createManagedConnectionFactory()
activate ConnectorDeployerImpl
deactivate ConnectorDeployerImpl
ConnectorDeployerImpl -> ConnectionPoolRegistry: register()
activate ConnectionPoolRegistry
note left
Create and register the real connection pool MBean
end note
ConnectionPoolRegistry -> ConnectionPool: new instance
activate ConnectionPool
note left
Create a connection pool object and put it in instancePools
Heartbeat thread will auto test all connection pool in instancePools
end note
ConnectionPool -> ConnectionPoolRegistry
deactivate ConnectionPool
ConnectionPoolRegistry -> MBeanServer: registerMBean()
activate MBeanServer
MBeanServer -> ConnectionPoolRegistry
deactivate MBeanServer
ConnectionPoolRegistry -> ConnectorDeployerImpl
deactivate ConnectionPoolRegistry
ConnectorDeployerImpl -> GenericConnectionPool
deactivate ConnectorDeployerImpl
GenericConnectionPool -> AnnotatedDynamicMBean
deactivate GenericConnectionPool

deactivate AnnotatedDynamicMBean
@enduml