@startuml
actor BSS

BSS -> PGNGN: HESPLSP
activate PGNGN

PGNGN -> MobileSubscriberLocationSurveyPrinter: process()
activate MobileSubscriberLocationSurveyPrinter

MobileSubscriberLocationSurveyPrinter -> MobileSubscriberLocationSurveyPrinter: writeSpecificSearchResult()
activate MobileSubscriberLocationSurveyPrinter

MobileSubscriberLocationSurveyPrinter -> MobileSubscriberLocationSurveyPrinter: searchAddresses()
activate MobileSubscriberLocationSurveyPrinter

MobileSubscriberLocationSurveyPrinter -> XMLReader: setContentHandler(this)
activate XMLReader
XMLReader -> MobileSubscriberLocationSurveyPrinter 
deactivate XMLReader

MobileSubscriberLocationSurveyPrinter -> XMLReader: parse(source)
activate XMLReader

XMLReader -> MobileSubscriberLocationSurveyPrinter:endElement
activate MobileSubscriberLocationSurveyPrinter
MobileSubscriberLocationSurveyPrinter -> XMLReader
deactivate MobileSubscriberLocationSurveyPrinter

XMLReader -> MobileSubscriberLocationSurveyPrinter 
deactivate XMLReader


deactivate MobileSubscriberLocationSurveyPrinter

deactivate MobileSubscriberLocationSurveyPrinter

MobileSubscriberLocationSurveyPrinter -> PGNGN:
deactivate MobileSubscriberLocationSurveyPrinter

PGNGN -> BSS
deactivate PGNGN

@enduml